### ISSUE TITLE
Unexpected Netty exception

### ISSUE THREAD

**Issue by debarshri** [webbit/webbit#142]
I am not sure what I am doing wrong. But I am getting this exception quite often.

Can some one explain in what scenario this happens and also if I am doing something wrong.

```
Sep 03, 2015 11:35:27 PM org.jboss.netty.channel.socket.nio.AbstractNioWorker
WARNING: Unexpected exception in the selector loop.
java.lang.NoClassDefFoundError: org/jboss/netty/util/internal/ByteBufferUtil
	at org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.newBuffer(SocketReceiveBufferAllocator.java:60)
	at org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.get(SocketReceiveBufferAllocator.java:46)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:67)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:390)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.util.internal.ByteBufferUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

**Comment by gabereiser** [comment]
looks like netty isn't in your classpath.  ClassNotFoundExceptions means it tried to load a class it couldn't find in it's classpath so either you are missing a dependency or you don't have that dependency as part of the classpath.  Are you using maven or gradle?
